<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WisataSeeder extends Seeder
{
    /**
     * Sync PENUH data ke tabel `wisatas`.
     * - Tambah data baru  ✅
     * - Update data lama  ✅
     * - Hapus data yang dihapus dari seeder  ✅
     *
     * Generate ulang file ini:
     *   php generate_seeders.php
     *
     * Jalankan seeder:
     *   php artisan db:seed --class=WisataSeeder
     */
    public function run(): void
    {
        $data = [
            [
                'nama'                 => 'Telaga Sarangan',
                'slug'                 => 'telaga-sarangan',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Jl. Raya Telaga Sarangan, Ngluweng, Sarangan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur 63361',
                'latitude'             => '-7.6678',
                'longitude'            => '111.2205',
                'maps'                 => 'https://maps.app.goo.gl/T8mBjbKqRhwKm1176',
                'harga_tiket'          => '20000.00',
                'jam_operasional'      => '07.00 - 17.00 WIB',
                'deskripsi'            => 'Telaga Sarangan, juga dikenal sebagai Telaga Pasir, adalah telaga alami yang berada di ketinggian 1.200 meter di atas permukaan laut dan terletak di lereng timur Gunung Lawu. Telaga ini memiliki luas sekitar 30 hektare dan kedalaman hingga 28 meter. Dengan suhu udara pegunungan yang sejuk antara 15 hingga 20 derajat Celcius, tempat ini menjadi destinasi favorit untuk bersantai. Pengunjung dapat menikmati pemandangan alam, berkeliling telaga menggunakan speedboat, atau menyewa kuda tunggang.',
                'fasilitas'            => 'Area Parkir Luas, Toilet Umum, Mushola, Warung Makan (Sate Kelinci), Penginapan / Hotel, Sewa Speedboat, Sewa Kuda Tunggang, Kios Souvenir.',
                'thumbnail'            => 'wisata/XgykPN9Z2HW7agkXn2a9ZOKICxKJe3sd5pzoRYXS.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 1,
                'pinned_at'            => '2026-08-04 10:35:49',
                'created_at'           => '2026-07-15 04:52:17',
                'updated_at'           => '2026-08-04 10:45:49',
            ],
            [
                'nama'                 => 'Mojosemi Forest Park',
                'slug'                 => 'mojosemi-forest-park',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Jl. Raya Sarangan, Cemorosewu Km. 5, Kali Jumok, Sarangan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur 63361',
                'latitude'             => '-7.6701',
                'longitude'            => '111.1972',
                'maps'                 => 'https://maps.app.goo.gl/w3HAJiRYTyLASV7w8',
                'harga_tiket'          => '35000.00',
                'jam_operasional'      => '08.00 - 16.00 WIB',
                'deskripsi'            => 'Mojosemi Forest Park adalah destinasi wisata keluarga yang memadukan keasrian hutan pinus di lereng Gunung Lawu dengan berbagai wahana hiburan seru. Daya tarik paling ikonik dari tempat ini adalah Mojosemi Dinosaurus Park, di mana pengunjung dapat menyusuri hutan sambil berinteraksi dengan puluhan replika dinosaurus raksasa berteknologi animatronik yang bisa bergerak dan bersuara layaknya hidup di habitat aslinya. Selain itu, tempat ini juga menawarkan udara pegunungan yang sangat segar dan berbagai aktivitas luar ruang.',
                'fasilitas'            => 'Area Parkir Luas, Toilet, Mushola, Food Court & Resto, Wahana Dinosaurus Park, Dino Show (Pertunjukan Dinosaurus), Outbound, Flying Fox, High Rope, Paintball, ATV, Glamping & Tenda Camp, Spot Foto Instagramable, Jeep Adventure.',
                'thumbnail'            => 'wisata/8DvgTZVZEUIK1Q0heGxnStjK4xBlY6sx55X8yd2t.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 1,
                'pinned_at'            => '2026-08-04 10:36:49',
                'created_at'           => '2026-07-20 07:17:52',
                'updated_at'           => '2026-08-04 10:45:49',
            ],
            [
                'nama'                 => 'Taman Wisata Genilangit',
                'slug'                 => 'taman-wisata-genilangit',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Poncol',
                'alamat'               => 'Desa Genilangit, Kecamatan Poncol, Kabupaten Magetan, Jawa Timur 63362',
                'latitude'             => '-7.7272',
                'longitude'            => '111.2341',
                'maps'                 => 'https://maps.app.goo.gl/1x7ujutSGigqMKAL9',
                'harga_tiket'          => '10000.00',
                'jam_operasional'      => '08.00 - 17.00 WIB',
                'deskripsi'            => 'Taman Wisata Genilangit adalah destinasi wisata alam kekinian yang terletak di kawasan perbukitan lereng Gunung Lawu. Menawarkan kombinasi sempurna antara panorama hutan pinus yang asri, udara pegunungan yang sejuk, dan deretan spot foto yang sangat instagramable. Tempat ini menjadi favorit wisatawan untuk berburu foto dengan latar belakang lembah hijau yang memukau, bersantai bersama keluarga, atau menikmati suasana tenang jauh dari hiruk-pikuk perkotaan.',
                'fasilitas'            => 'Area Parkir, Mushola, Toilet Umum, Warung Kuliner & Kopi, Gazebo / Tempat Istirahat, Spot Foto Kreatif (Sepeda Gantung, Perahu Kayu di Pinggir Tebing, Rumah Pohon, Sayap Kupu-Kupu), Area Bermain Anak, Flying Fox, Penyewaan Kostum Jepang/Kimono.',
                'thumbnail'            => 'wisata/UOZJMA136yBhMDMOZWsRDBby5W5vtAxAzqkpXYQ5.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 1,
                'pinned_at'            => '2026-08-04 10:37:49',
                'created_at'           => '2026-07-20 07:46:09',
                'updated_at'           => '2026-08-04 10:45:49',
            ],
            [
                'nama'                 => 'Sgodean (Kolam Renang & Cafe)',
                'slug'                 => 'sgodean-kolam-renang-cafe',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Panekan',
                'alamat'               => 'Jl. Raya Jabung, Bulusari, Jabung, Panekan, Kabupaten Magetan, Jawa Timur 63352',
                'latitude'             => '-7.6122146',
                'longitude'            => '111.2719443',
                'maps'                 => 'https://maps.app.goo.gl/pRD3APFvi5KB3J9LA',
                'harga_tiket'          => '5000.00',
                'jam_operasional'      => '08.00 - 16.00 WIB',
                'deskripsi'            => 'Sgodean adalah destinasi wisata air tersembunyi yang sedang populer di kawasan Ngiliran, Kecamatan Panekan, Magetan. Tempat ini menawarkan pesona kolam pemandian terbuka yang luas dengan air yang sangat jernih dan menyegarkan. Dikelilingi oleh pepohonan dan suasana alam yang asri, pengunjung dapat berenang santai menggunakan ban pelampung. Selain bermain air, Sgodean juga terintegrasi dengan area kafe, menjadikannya lokasi yang sangat cocok untuk rekreasi keluarga atau sekadar healing santai bersama teman-teman.',
                'fasilitas'            => 'Kolam Renang Terbuka, Penyewaan Ban Pelampung, Cafe & Restoran, Area Parkir Kendaraan, Kamar Bilas / Toilet, Tempat Duduk / Area Santai.',
                'thumbnail'            => 'wisata/1tjF1zw9lQuxKcip1YZmtpriaONyXYXCcDpOQsV8.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 03:05:29',
                'updated_at'           => '2026-07-22 03:05:29',
            ],
            [
                'nama'                 => 'Situs Candi Sadon (Candi Reog)',
                'slug'                 => 'situs-candi-sadon-candi-reog',
                'kategori'             => 'Budaya',
                'kecamatan'            => 'Panekan',
                'alamat'               => 'Dusun Sadon, Desa Cepoko, Kecamatan Panekan, Kabupaten Magetan, Jawa Timur 63352',
                'latitude'             => '-7.6256',
                'longitude'            => '111.2987',
                'maps'                 => 'https://maps.app.goo.gl/sqcdMGL982da5knd6',
                'harga_tiket'          => '0.00',
                'jam_operasional'      => '08.00 - 16.00 WIB',
                'deskripsi'            => 'Situs Candi Sadon, atau yang populer di kalangan masyarakat lokal dengan sebutan Candi Reog, adalah sebuah situs cagar budaya peninggalan masa klasik (Hindu) yang berada di Magetan. Dinamakan Candi Reog karena pada salah satu batu candi (Kala) terdapat pahatan wajah yang dipercaya masyarakat mirip dengan topeng dadak merak pada kesenian Reog Ponorogo. Di situs ini, wisatawan dapat mengamati susunan batu andesit kuno dan peninggalan arca lembu (Nandi). Destinasi ini sangat tepat untuk wisata edukasi, penelitian sejarah, dan pengenalan budaya bagi pelajar maupun keluarga yang ingin melihat langsung jejak peradaban masa lampau di lereng Gunung Lawu.',
                'fasilitas'            => 'Area Parkir (terbatas), Papan Informasi Sejarah Cagar Budaya, Gazebo / Tempat Istirahat, Juru Pelihara (Jupel) yang siap memandu menceritakan sejarah situs.',
                'thumbnail'            => 'wisata/Bu9lPpm9ZDxRz1zN5TBIoJwmlqlbe45j7ofOuZjq.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 10:22:35',
                'updated_at'           => '2026-07-22 10:23:55',
            ],
            [
                'nama'                 => 'Masjid Agung Baitussalam Magetan',
                'slug'                 => 'masjid-agung-baitussalam-magetan',
                'kategori'             => 'Religi',
                'kecamatan'            => 'Magetan',
                'alamat'               => 'Jl. Basuki Rahmat Barat No.1, Tambran, Kec. Magetan, Kabupaten Magetan, Jawa Timur 63314 (Tepat di sebelah barat Alun-Alun Magetan)',
                'latitude'             => '-7.6166',
                'longitude'            => '111.3259',
                'maps'                 => 'https://maps.app.goo.gl/9bav1Sz3B7ALpc5N6',
                'harga_tiket'          => '0.00',
                'jam_operasional'      => '24 Jam',
                'deskripsi'            => 'Masjid Agung Baitussalam merupakan masjid utama dan terbesar di Kabupaten Magetan yang berlokasi sangat strategis, berdampingan langsung dengan Alun-Alun kota. Masjid ini memiliki arsitektur megah dengan perpaduan gaya klasik dan modern yang indah, serta memiliki menara yang menjulang tinggi. Selain menjadi pusat ibadah masyarakat Magetan, masjid ini sering menjadi destinasi wisata religi bagi para musafir atau rombongan wisatawan dari luar kota. Suasananya yang sejuk, bersih, dan tenang menjadikannya tempat yang sempurna untuk beri\'tikaf, beribadah, sekaligus beristirahat sejenak sebelum melanjutkan perjalanan wisata di Magetan.',
                'fasilitas'            => 'Area Parkir Luas (terintegrasi dengan area Alun-Alun), Tempat Wudhu Pria & Wanita yang bersih, Toilet Umum, Ruang Penitipan Sandal/Barang, Peminjaman Mukena & Sarung, Area Istirahat (Serambi), serta akses pejalan kaki yang sangat dekat dengan pusat kuliner dan suvenir di sekitar Alun-Alun Magetan.',
                'thumbnail'            => 'wisata/K4DtPvSvktY3Tw6sR13uLLyHtGxj1MNTy9vQJEy6.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 10:38:28',
                'updated_at'           => '2026-07-22 10:38:28',
            ],
            [
                'nama'                 => 'Magetan Park',
                'slug'                 => 'magetan-park',
                'kategori'             => 'Buatan',
                'kecamatan'            => 'Magetan',
                'alamat'               => 'Jl. Pahlawan No.14, Tambran, Kec. Magetan, Kabupaten Magetan, Jawa Timur 63318',
                'latitude'             => '-7.6191',
                'longitude'            => '111.3275',
                'maps'                 => 'https://maps.app.goo.gl/Z9oGkSzukXu19Cew5',
                'harga_tiket'          => '20000.00',
                'jam_operasional'      => '08.00 - 16.00 WIB (Biasanya tutup pada hari Senin untuk pemeliharaan)',
                'deskripsi'            => 'Magetan Park adalah taman rekreasi keluarga berkonsep wisata buatan terpadu yang berada di jantung kota Magetan. Destinasi ini memadukan keseruan wahana permainan air (waterpark) dengan aktivitas luar ruangan (outbound) dalam satu kawasan yang rindang dan tertata rapi. Pengunjung dapat menikmati berbagai wahana seperti kolam renang anak dan dewasa, perosotan air (waterboom), ember tumpah, hingga wahana memacu adrenalin seperti flying fox dan high rope. Tempat ini menjadi pilihan favorit bagi keluarga, rombongan sekolah, maupun instansi yang ingin mengadakan acara family gathering di lokasi yang mudah diakses.',
                'fasilitas'            => 'Kolam Renang (Waterboom), Wahana Outbound (Flying Fox, ATV), Loker Penitipan Barang, Kamar Bilas dan Toilet yang bersih, Food Court / Kantin, Gazebo untuk bersantai, Mushola, dan Area Parkir yang memadai.',
                'thumbnail'            => 'wisata/boxrLlHvv8ppUQ2PKUEdfuEYTm2MK1NQD39k6CWG.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 10:45:14',
                'updated_at'           => '2026-07-22 10:46:16',
            ],
            [
                'nama'                 => 'Kampung Susu Lawu Singolangu',
                'slug'                 => 'kampung-susu-lawu-singolangu',
                'kategori'             => 'Edukasi',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Kali Jumok, Sarangan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur 63361',
                'latitude'             => '-7.6740',
                'longitude'            => '111.2335',
                'maps'                 => 'https://maps.app.goo.gl/vUhdsKJCNwbmm78D8',
                'harga_tiket'          => '5000.00',
                'jam_operasional'      => '08.00 - 16.00 WIB',
                'deskripsi'            => 'Kampung Susu Lawu Singolangu merupakan destinasi wisata edukasi unggulan di Magetan yang berlokasi tidak jauh dari Telaga Sarangan. Mengusung konsep agrowisata, KSL mengajak pengunjung untuk belajar dan berinteraksi langsung dengan kegiatan peternakan sapi perah. Wisatawan, khususnya anak-anak dan pelajar, dapat mengikuti paket edukasi yang meliputi kegiatan memerah susu sapi, memberi makan pedet (anak sapi), hingga melihat langsung proses pengolahan susu segar menjadi aneka produk lezat seperti susu pasteurisasi, yoghurt, dan permen karamel susu. Didukung udara pegunungan Lawu yang sejuk, belajar di KSL menjadi pengalaman liburan yang menyenangkan sekaligus menambah wawasan.',
                'fasilitas'            => 'Area Parkir, Pemandu Wisata Edukasi (untuk rombongan), Kandang Percontohan, Kedai Susu & Pusat Oleh-oleh Olahan Susu, Spot Foto, Toilet Bersih, dan Gazebo / Area Kumpul Rombongan.',
                'thumbnail'            => 'wisata/DQARnhHHrlQoMC9zRh9mar8336k2SJUkBfFh9ljn.webp',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 10:58:29',
                'updated_at'           => '2026-07-22 11:00:03',
            ],
            [
                'nama'                 => 'Sentra Kuliner Ayam Panggang Gandu',
                'slug'                 => 'sentra-kuliner-ayam-panggang-gandu',
                'kategori'             => 'Kuliner',
                'kecamatan'            => 'Karangrejo',
                'alamat'               => 'Desa Gandu, Kecamatan Karangrejo, Kabupaten Magetan, Jawa Timur 63375',
                'latitude'             => '-7.5684',
                'longitude'            => '11.4121',
                'maps'                 => 'https://maps.app.goo.gl/9ka2STuwYTBXUQr69',
                'harga_tiket'          => '0.00',
                'jam_operasional'      => '08.00 - 20.00 WIB',
                'deskripsi'            => 'Desa Gandu telah lama dikenal sebagai surga kuliner ayam panggang tradisional yang legendaris di Magetan. Saat memasuki kawasan desa ini, pengunjung akan langsung disambut oleh aroma sedap kepulan asap dari dapur-dapur rumah warga. Keunikan dari Ayam Panggang Gandu adalah proses memasaknya yang masih mempertahankan cara tradisional, yakni dipanggang di atas tungku tanah liat menggunakan kayu bakar. Hal ini menghasilkan cita rasa bumbu yang meresap sempurna, daging yang empuk, dan aroma smokey yang khas. Pengunjung disuguhkan pengalaman makan yang otentik karena bisa langsung melihat proses pemanggangan di dapur warga (konsep open kitchen tradisional) dan menyantap hidangan secara lesehan bersama keluarga.',
                'fasilitas'            => 'Area Parkir (tersedia di halaman masing-masing rumah makan warga), Ruang Makan Lesehan yang luas dan nyaman, Konsep Dapur Terbuka, Toilet Bersih, Mushola, dan beberapa warga juga menjual oleh-oleh khas Magetan lainnya seperti kerupuk lempeng/karak.',
                'thumbnail'            => 'wisata/OKLx9iStv2G06JZakmmHIMhAtl0JoLZDhQ8snMvb.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 11:08:22',
                'updated_at'           => '2026-07-22 11:19:42',
            ],
            [
                'nama'                 => 'Wisata Paralayang Gunung Blego',
                'slug'                 => 'wisata-paralayang-gunung-blego',
                'kategori'             => 'Olahraga',
                'kecamatan'            => 'Parang',
                'alamat'               => '67MW+G4R, Gn. Blego, Sayutan, Kec. Parang, Kabupaten Magetan, Jawa Timur 63371',
                'latitude'             => '-7.6985',
                'longitude'            => '111.3092',
                'maps'                 => 'https://maps.app.goo.gl/Q7rphyfNxNVCv3Gy7',
                'harga_tiket'          => '5000.00',
                'jam_operasional'      => '08.00 - 17.00 WIB (Waktu operasional sangat bergantung pada kondisi cuaca dan arah angin)',
                'deskripsi'            => 'Gunung Blego menawarkan daya tarik utama berupa wisata olahraga dirgantara, khususnya paralayang (paragliding). Dengan ketinggian dan kontur alam yang ideal, lokasi ini menjadi titik lepas landas (take-off) favorit bagi para atlet paralayang maupun wisatawan yang ingin memacu adrenalin melalui penerbangan tandem. Selain menikmati sensasi terbang bebas di udara, pengunjung akan dimanjakan dengan panorama alam Magetan dari ketinggian, hamparan perbukitan hijau, dan hembusan angin pegunungan yang segar. Destinasi ini juga sangat cocok bagi fotografer atau wisatawan yang sekadar ingin refreshing sambil menonton paralayang yang sedang mengudara.',
                'fasilitas'            => 'Landasan Pacu / Titik Lepas Landas (Take-off Area), Area Pendaratan (Landing Area), Jasa Terbang Tandem dengan Instruktur Berlisensi, Area Parkir Kendaraan, Warung Makan/Kopi sederhana milik warga sekitar, dan Spot Foto panorama ketinggian.',
                'thumbnail'            => 'wisata/Vz6PZKD2va0ZG3lUZm2j37vzMJYTS8GDYaun7obn.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-22 11:26:32',
                'updated_at'           => '2026-07-22 11:26:32',
            ],
            [
                'nama'                 => 'Air Terjun Tirtosari',
                'slug'                 => 'air-terjun-tirtosari',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Desa Ngancar, Kecamatan Plaosan, Kabupaten Magetan, Jawa Timur.',
                'latitude'             => '-7.679',
                'longitude'            => '111.2297',
                'maps'                 => 'https://maps.google.com/?q=Air+Terjun+Tirtosari+Magetan',
                'harga_tiket'          => '10000.00',
                'jam_operasional'      => '07.00 - 17.00 WIB',
                'deskripsi'            => 'Air Terjun Tirtosari atau dikenal juga sebagai Grojogan Tirtosari merupakan salah satu destinasi wisata alam unggulan di Kabupaten Magetan. Air terjun ini memiliki ketinggian sekitar 50 meter dengan aliran air yang jernih dan suasana pegunungan yang sejuk. Lokasinya berada di kaki Gunung Lawu sehingga dikelilingi pepohonan hijau yang masih alami. Pengunjung dapat menikmati pemandangan alam, berfoto, serta berjalan melalui jalur trekking yang telah disediakan. Destinasi ini sangat cocok untuk wisata keluarga maupun pecinta alam yang ingin menikmati suasana tenang dan udara segar.',
                'fasilitas'            => 'Area parkir
Toilet
Mushola
Warung makan
Gazebo
Jalur trekking
Spot foto',
                'thumbnail'            => 'wisata/yKxlwxEMjyaTkf4WMPOqTWmezj01xVYiD0rmnW1a.webp',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-07-28 10:32:43',
                'updated_at'           => '2026-07-28 10:32:43',
            ],
            [
                'nama'                 => 'Taman Bunga Refugia',
                'slug'                 => 'taman-bunga-refugia',
                'kategori'             => 'Buatan',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Jl. Raya Sarangan, Plaosan II, Plaosan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur',
                'latitude'             => '-7.6813677',
                'longitude'            => '111.2535154',
                'maps'                 => 'https://maps.app.goo.gl/Am5unTEq3zkcnZg2A',
                'harga_tiket'          => '10000.00',
                'jam_operasional'      => '08.00 - 17.00 WIB',
                'deskripsi'            => 'Taman Bunga Refugia adalah hamparan bunga warna-warni yang tertata rapi membentuk lautan warna di antara udara sejuk khas pegunungan. Refugia juga dikenal sebagai wisata edukatif berbasis agrowisata, di mana pengunjung, khususnya anak-anak dapat belajar tentang proses menanam dan mengenal berbagai jenis tanaman hortikultura.Ada pula taman kelinci, tempat anak-anak bisa berinteraksi langsung dengan hewan lucu tersebut, memberi makan, atau berfoto di depan ikon patung kelinci yang menjadi simbol taman. Selain itu, terdapat menara pandang setinggi 15 meter yang memungkinkan pengunjung menikmati panorama Magetan dari ketinggian.Beberapa gazebo disediakan untuk bersantai sambil menikmati camilan atau hidangan ringan dari warung sekitar. Bagi rombongan sekolah atau kantor, tersedia pula area outbound yang bisa digunakan untuk kegiatan kelompok dan permainan edukatif',
                'fasilitas'            => 'Parkir, Toilet, Warung Makan, Gazebo, Area Outbound, Spot Foto',
                'thumbnail'            => 'wisata/kENGLrHJUp6l84rggdYkbHBSiwygQyKexuLUt1Gk.jpg',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-08-03 09:05:10',
                'updated_at'           => '2026-08-03 09:05:10',
            ],
            [
                'nama'                 => 'Telaga Wahyu',
                'slug'                 => 'telaga-wahyu',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Plaosan III, Plaosan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur',
                'latitude'             => '-7.681498',
                'longitude'            => '111.250550',
                'maps'                 => 'https://maps.app.goo.gl/XofZBN4jnq6MnzvHA',
                'harga_tiket'          => '5000.00',
                'jam_operasional'      => '08.00 - 18.00 WIB (Catatan: Wisata ini buka setiap hari dari pagi hingga menjelang petang).',
                'deskripsi'            => 'Telaga wahyu dulunya bernama Telaga Wurung. Dinamai demikian karena terdapat mitos bahwa jika sepasang kekasih pergi ke sini, maka cepat atau lambat hubungan mereka akan berakhir. Nama Wurung berasal dari kata urung. Guna menghilangkan kekhawatiran pengunjung, maka nama Telaga Wurung diganti menjadi Telaga Wahyu. Mitos itu pun sebenarnya tidak terbukti dan hanya merupakan alasan bagi pasangan yang memang sudah ingin mengakhiri hubungan. Telaga wahyu digunakan untuk memancing ikan',
                'fasilitas'            => 'Area Parkir Kendaraan, Toilet Umum, Warung Kuliner Tradisional, Wahana Becak Air (Perahu Bebek), Spot Memancing, Gazebo, Area Berkemah (Camping Ground).',
                'thumbnail'            => 'wisata/lu2yNxYIVI1yNiPfXZkfcvGre9a4Zz2VfO3Edf6p.png',
                'status_publish'       => 1,
                'is_pinned'            => 0,
                'pinned_at'            => NULL,
                'created_at'           => '2026-08-03 09:17:00',
                'updated_at'           => '2026-08-03 09:17:00',
            ],
            [
                'nama'                 => 'Lawu Green Forest (LGF) Magetan',
                'slug'                 => 'lawu-green-forest-lgf-magetan',
                'kategori'             => 'Alam',
                'kecamatan'            => 'Plaosan',
                'alamat'               => 'Jl. Sarangan-Cemorosewu Km, Kali Jumok, Sarangan, Kec. Plaosan, Kabupaten Magetan, Jawa Timur',
                'latitude'             => '-7.663707',
                'longitude'            => '111.218171',
                'maps'                 => 'https://maps.app.goo.gl/NUAa5ZSa64rH8qCe8',
                'harga_tiket'          => '20000.00',
                'jam_operasional'      => '08.00 - 17.00 WIB',
                'deskripsi'            => 'Lawu green forest merupakan wisata alam dengan latar belakang pepohonan pinus yang asri, berada di kawasan pegunungan. Memiliki daya tarik wisata berkemah dengan nuansa alam hutan pinus, bermain outbound dengan konsep edukasi dan outdoor creative program activity ( Fun Outdoor, Educational Fun Outdoor Program, dan Fun Develop Outdoor Activity Program), wahana rainbow slide, bangunan/spot foto unik-unik instagramable, jeep dan atv, kampung jepang, dan taman bunga.',
                'fasilitas'            => 'Area Parkir Luas, Toilet, Mushola, Restoran, Villa & Glamping, Rainbow Slide, Tamiya Coaster, Wahana Miniatur Dunia, Outbound & Camping Ground.',
                'thumbnail'            => 'wisata/0iOSV09ArBZR9HpEn53hRLwu9ljQcXi1YYZiOLkW.webp',
                'status_publish'       => 1,
                'is_pinned'            => 1,
                'pinned_at'            => '2026-08-04 10:38:49',
                'created_at'           => '2026-08-03 10:21:41',
                'updated_at'           => '2026-08-04 10:45:49',
            ],
        ];

        // ── Hapus data yang sudah tidak ada di seeder ──
        $activeKeys = array (
  0 => 'telaga-sarangan',
  1 => 'mojosemi-forest-park',
  2 => 'taman-wisata-genilangit',
  3 => 'sgodean-kolam-renang-cafe',
  4 => 'situs-candi-sadon-candi-reog',
  5 => 'masjid-agung-baitussalam-magetan',
  6 => 'magetan-park',
  7 => 'kampung-susu-lawu-singolangu',
  8 => 'sentra-kuliner-ayam-panggang-gandu',
  9 => 'wisata-paralayang-gunung-blego',
  10 => 'air-terjun-tirtosari',
  11 => 'taman-bunga-refugia',
  12 => 'telaga-wahyu',
  13 => 'lawu-green-forest-lgf-magetan',
);
        $deleted = DB::table('wisatas')
            ->whereNotIn('slug', $activeKeys)
            ->delete();
        if ($deleted > 0) {
            $this->command->warn("  ⚠ Dihapus {$deleted} data lama dari `wisatas`.");
        }

        // ── Tambah / update data dari seeder ──
        foreach ($data as $item) {
            DB::table('wisatas')->updateOrInsert(
                ['slug' => $item['slug']],
                $item
            );
        }

        $this->command->info('✓ WisataSeeder: ' . count($data) . ' data aktif di database.');
    }
}
